# Generated by Django 4.2.4 on 2023-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_following',
            field=models.BooleanField(default=False),
        ),
    ]
