# Generated by Django 4.2.4 on 2023-09-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_follow_is_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_following',
        ),
    ]
