# Generated by Django 4.2.4 on 2023-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/Profile.png', null=True, upload_to='profile/'),
        ),
    ]
